version: "3.8"

services:
  chatpdf-app:
    container_name: ${PREFIX}-app
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        KEYCLOAK_SECRET: ${KEYCLOAK_SECRET}
        KEYCLOAK_ISSUER: ${KEYCLOAK_ISSUER}
        KEYCLOAK_ID: ${KEYCLOAK_ID}
        DATABASE_URL: ${DATABASE_URL}
        CHROMA_API_IMPL: ${CHROMA_API_IMPL}
        CHROMA_SERVER_HOST: ${CHROMA_SERVER_HOST}
        CHROMA_SERVER_HTTP_PORT: ${CHROMA_SERVER_HTTP_PORT}
        NUTPROJECT_ACCESS_TOKEN_PLAIN: ${NUTPROJECT_ACCESS_TOKEN_PLAIN}
        NUTPROJECT_ACCESS_TOKEN_SECRET: ${NUTPROJECT_ACCESS_TOKEN_SECRET}
        NUTPROJECT_ACCESS_TOKEN_IV: ${NUTPROJECT_ACCESS_TOKEN_IV}
        MINIO_ENDPOINT: ${MINIO_ENDPOINT}
        MINIO_PORT: ${MINIO_PORT}
        MINIO_USESSL: ${MINIO_USESSL}
        MINIO_ACCESSKEY: ${MINIO_ACCESSKEY}
        MINIO_SECRETKEY: ${MINIO_SECRETKEY}
        MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
        PORT: ${PORT}
    restart: always
    env_file:
      - .env
    ports:
      - 3002:3002
    image: ${CHATPDF_IMAGE_NAME}:${CHATPDF_IMAGE_VERSION}
    networks:
      chatpdf_net:
        aliases:
          - ${PREFIX}-app

  minio:
    container_name: ${PREFIX}-minio
    image: minio/minio
    ports:
      - "9040:9000"
      - "9041:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: wKoxIXEmEX00OwOJ
      MINIO_ROOT_PASSWORD: xL9.CaGNR#nIEZ0m=NoD#pwX8nwFNM7e
    command: server --console-address ":9001" /data
    networks:
      chatpdf_net:
        aliases:
          - ${PREFIX}-minio
  minio-init:
    image: minio/mc
    command:
      [
        "sh",
        "-c",
        "chmod +x /docker-entrypoint-initdb.d/init_minio.sh && /docker-entrypoint-initdb.d/init_minio.sh",
      ]
    volumes:
      - ./minio/init_minio.sh:/docker-entrypoint-initdb.d/init_minio.sh
    entrypoint: [""]
    depends_on:
      - minio
    networks:
      nut_net:
        aliases:
          - chatpdf-minio-init
  chromadb:
    container_name: ${PREFIX}-chromadb
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chroma_persistent_folder:/chroma/chroma/
      # - ./chromadb/log_config.yml:chromadb/log_config.yml
      # Be aware that indexed data are located in "/chroma/chroma/"
      # Default configuration for persist_directory in chromadb/config.py
    # ommand: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config chromadb/log_config.yml
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=${PERSIST_DIRECTORY:-/chroma/chroma}
    ports:
      - 8001:8000
    networks:
      chatpdf_net:
        aliases:
          - ${PREFIX}-chromadb

volumes:
  chroma_persistent_folder:
    driver: local
  minio_data:
    driver: local

networks:
  chatpdf_net:
    driver: bridge
    name: chatpdf_net
  nut_net:
    external: true
