# https://github.com/chroma-core/chroma/blob/main/docker-compose.yml
version: "3.8"
services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chroma_persistent_folder:/chroma/chroma/
      # - ./chromadb/log_config.yml:chromadb/log_config.yml
      # Be aware that indexed data are located in "/chroma/chroma/"
      # Default configuration for persist_directory in chromadb/config.py
    # ommand: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config chromadb/log_config.yml
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=${PERSIST_DIRECTORY:-/chroma/chroma}
    ports:
      - 8001:8000
    networks:
      - chatpdf_net

volumes:
  chroma_persistent_folder:
    driver: local
networks:
  chatpdf_net:
    driver: bridge
    name: chatpdf_net
