version: "3.8"

services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9040:9000"
      - "9041:9001"
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: wKoxIXEmEX00OwOJ
      MINIO_ROOT_PASSWORD: xL9.CaGNR#nIEZ0m=NoD#pwX8nwFNM7e
    command: server --console-address ":9001" /data
    networks:
      - chatpdf_net
networks:
  chatpdf_net:
    driver: bridge
    name: chatpdf_net
